### ISSUE TITLE
does it work from Slate to Markdown too?

### ISSUE THREAD

**Issue by horacioh** [hanford/remark-slate#1]
I dunno if this is correct but, can I use this same plugin to convert Slate values to markdown?

thanks in advance!

**Comment by hanford** [comment]
You can't use it for slate -> markdown, but here is some code I'm using to serialize slate state -> markdown


https://gist.github.com/hanford/fa61e86a8559d2e50941f88be8b18b30


Going to go ahead and close this issue. I hope the above snippet works for you!

**Comment by horacioh** [comment]
thanks!!

**Comment by TrySpace** [comment]
So `import { serialize } from 'remark-slate';` is not meant to be used? 

Because, it's working partially: It's not parsing newlines. Also not with: `value.map((v) => serialize(v)).join('\n')` And links are not parsed...

**Comment by hanford** [comment]
@TrySpace for links in my editor, I use something like this: https://gist.github.com/hanford/86aa09b3f1a2e937787791297f349545

remark-slate should handle serializing and deserializing though:

https://github.com/hanford/remark-slate/blob/master/test/deserialize/link.test.ts
https://github.com/hanford/remark-slate/blob/master/test/serialize/serialize-link.test.ts

**Comment by TrySpace** [comment]
@hanford thanks, but I don't see the difference, and don't really understand why both serialize AND deserialize want an object. 

What I'm looking for is a function that accepts a `string` of markdown and converts it to slate.

I mean, looking at these tests: https://github.com/hanford/remark-slate/blob/master/test/deserialize/transform.test.ts 

```ts
 deserialize({ type: 'heading', depth: 1, children: [{ value: 'hey' }] })
```
That basically looks like a slate object, so I'm not sure what the expected usecase for this is...

**Comment by hanford** [comment]
@TrySpace remark-slate works on `mdast` which is a markdown AST, the structure the deserialize tests is using isn't a slate object, it's an [mdast node](https://github.com/syntax-tree/mdast) provided by remark.

> That basically looks like a slate object, so I'm not sure what the expected usecase for this is...

It's actually mocking what remark would passes to remark-slate, while it's similar to the slate state, the two aren't the same.

I believe the example script is roughly what you want:

```
import unified from 'unified';
import markdown from 'remark-parse';
import slate from 'remark-slate';

unified()
  .use(markdown)
  .use(slate)
  .process("[my link](https://github.com)", (err, file) => {
    if (err) throw err;
    console.log({ res: file.result });
  });
```

I've [updated the readme](https://github.com/hanford/remark-slate/commit/41ef1fef337acc695d658ab5cea8256f69467575) to hopefully be more clear, and I've added another test using unfied and remark-parse to outline the basic usage.

Let me know if you have any more questions, a new issue would probably be best.
