### ISSUE TITLE
Code blocks support

### ISSUE THREAD

**Issue by hadrysmateusz** [hanford/remark-slate#12]
Is support for code blocks planned?

**Comment by hanford** [comment]
I'm not using that currently so I probably won't add that support, but I would accept a PR!

**Comment by hadrysmateusz** [comment]
Sure. I would love to make a PR, in fact I think I've already got deserializing working but my testing knowledge is basically non-existent at the moment.

**Comment by hadrysmateusz** [comment]
I created a pull request, hopefully the tests are enough #13
