### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [hanford/remark-slate#17]
Hi!

remark is switching to a new parser (and compiler) internally ([micromark](https://github.com/micromark/micromark), see [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536) for more info).
From a quick glance at the code, it seems this plugin should be fine. However, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by hanford** [comment]
Oh cool, I'll take a look this week ... really appreciate all of the work you've been doing done @wooorm 😍

**Comment by hanford** [comment]
@wooorm upgrading `remark` and `remark-parse` to the latest alphas, 48/48 tests still passing ✅ 🤗

I'll merge / release once `remark` and `remark-parse` majors are released. Thanks again!
