### ISSUE TITLE
accept custom slate node types

### ISSUE THREAD

**Issue by horacioh** [hanford/remark-slate#2]
Currently I'm using this plugin to parse markdown content to slate nodes and works perfect!!

one thing that it would be nice is to accept the user's custom slate node types to make it more customisable.

for example: my paragraph type key is `p` instead of `paragraph`

### The solution I suggest

we can just accept a key-value object to match the MDAST type to whatever you want using a closure like so:

```js
import fs from 'fs';
import unified from 'unified';
import markdown from 'remark-parse';
import slate from 'remark-slate';

const myNodeTypes = {
  'paragraph': 'p',
  'ul_list': 'ul',
  'ol_list': 'ol',
  'list_item': 'li'
  // ...
}
unified()
  .use(markdown)
  .use(slate(myNodeTypes))
  .process(fs.readFileSync('example.md'), (err, file) => {
    if (err) throw err;
    console.log({ file });
  });
```

this is kinda simple change to do, but is a breaking change, that's why i found it better to discuss it first

hope it's clear!, and let me know any questions/feedback!
cc @hanford

**Comment by hanford** [comment]
@horacioh I think this is a good idea, one of small change is I think the way we should pass options into remark should be like this:

`.use(slate, {nodeTypes: myNodeTypes})`

I think that's the more standard remark-y way of doing it
