### ISSUE TITLE
Create new release for image component

### ISSUE THREAD

**Issue by pradel** [hanford/remark-slate#48]
Version 1.8.0 does not contain the latest fix that adds the image to the list of void elements (pr https://github.com/hanford/remark-slate/pull/46).

@hanford would it be possible to get a new release please 🙏 

Edit: released a forked version under `@sigle/remark-slate` while waiting for an official release if anyone needs the release too :)

**Comment by hanford** [comment]
Should be live in version `1.8.2`. Let me know if it's not!

**Comment by pradel** [comment]
Perfect, thanks!
